FUNCTION-POOL ZCO_FG06 MESSAGE-ID ZCO01.

* INCLUDE LZCO_FG06D...                      " Local class definition





CONSTANTS GC_KTOPL TYPE KTOPL VALUE '1000'.


DEFINE _CONVERSION_IN.
  CALL FUNCTION 'CONVERSION_EXIT_ALPHA_INPUT'
  EXPORTING
  input = &1
  IMPORTING
  output = &1.
END-OF-DEFINITION.

DEFINE _CONVERSION_OUT.
  CALL FUNCTION 'CONVERSION_EXIT_ALPHA_OUTPUT'
  EXPORTING
  input = &1
  IMPORTING
  output = &1.
END-OF-DEFINITION.
