*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZCOV000.........................................*
FORM GET_DATA_ZCOV000.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZCOT000 WHERE
(VIM_WHERETAB) .
    CLEAR ZCOV000 .
ZCOV000-MANDT =
ZCOT000-MANDT .
ZCOV000-BUKRS =
ZCOT000-BUKRS .
ZCOV000-FLAG =
ZCOT000-FLAG .
ZCOV000-AEDAT =
ZCOT000-AEDAT .
ZCOV000-AENAM =
ZCOT000-AENAM .
ZCOV000-AEZET =
ZCOT000-AEZET .
    SELECT SINGLE * FROM T001 WHERE
BUKRS = ZCOT000-BUKRS .
    IF SY-SUBRC EQ 0.
ZCOV000-BUTXT =
T001-BUTXT .
    ENDIF.
<VIM_TOTAL_STRUC> = ZCOV000.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZCOV000 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZCOV000.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZCOV000-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZCOT000 WHERE
  BUKRS = ZCOV000-BUKRS .
    IF SY-SUBRC = 0.
    DELETE ZCOT000 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZCOT000 WHERE
  BUKRS = ZCOV000-BUKRS .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZCOT000.
    ENDIF.
ZCOT000-MANDT =
ZCOV000-MANDT .
ZCOT000-BUKRS =
ZCOV000-BUKRS .
ZCOT000-FLAG =
ZCOV000-FLAG .
ZCOT000-AEDAT =
ZCOV000-AEDAT .
ZCOT000-AENAM =
ZCOV000-AENAM .
ZCOT000-AEZET =
ZCOV000-AEZET .
    IF SY-SUBRC = 0.
    UPDATE ZCOT000 ##WARN_OK.
    ELSE.
    INSERT ZCOT000 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZCOV000-UPD_FLAG,
STATUS_ZCOV000-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ENTRY_ZCOV000.
  SELECT SINGLE * FROM ZCOT000 WHERE
BUKRS = ZCOV000-BUKRS .
ZCOV000-MANDT =
ZCOT000-MANDT .
ZCOV000-BUKRS =
ZCOT000-BUKRS .
ZCOV000-FLAG =
ZCOT000-FLAG .
ZCOV000-AEDAT =
ZCOT000-AEDAT .
ZCOV000-AENAM =
ZCOT000-AENAM .
ZCOV000-AEZET =
ZCOT000-AEZET .
    SELECT SINGLE * FROM T001 WHERE
BUKRS = ZCOT000-BUKRS .
    IF SY-SUBRC EQ 0.
ZCOV000-BUTXT =
T001-BUTXT .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZCOV000-BUTXT .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZCOV000 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZCOV000-BUKRS TO
ZCOT000-BUKRS .
MOVE ZCOV000-MANDT TO
ZCOT000-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZCOT000'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZCOT000 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZCOT000'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZCOV000 USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZCOT000-MANDT =
ZCOV000-MANDT .
ZCOT000-BUKRS =
ZCOV000-BUKRS .
ZCOT000-FLAG =
ZCOV000-FLAG .
ZCOT000-AEDAT =
ZCOV000-AEDAT .
ZCOT000-AENAM =
ZCOV000-AENAM .
ZCOT000-AEZET =
ZCOV000-AEZET .
    SELECT SINGLE * FROM T001 WHERE
BUKRS = ZCOT000-BUKRS .
    IF SY-SUBRC EQ 0.
ZCOV000-BUTXT =
T001-BUTXT .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZCOV000-BUTXT .
    ENDIF.
ENDFORM.
