*&---------------------------------------------------------------------*
*& Include          ZCOR101_SCR
*&---------------------------------------------------------------------*.
SELECTION-SCREEN FUNCTION KEY 1.

SELECTION-SCREEN BEGIN OF BLOCK BL1 WITH FRAME.
PARAMETERS: P_VKOKR TYPE PROJ-VKOKR OBLIGATORY,  "관리회계영역
            P_GJAHR TYPE MSEG-GJAHR OBLIGATORY.  "시작년도

SELECTION-SCREEN SKIP 2.
SELECTION-SCREEN COMMENT 1(79) TEXT-T01.

SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS RB_CRT RADIOBUTTON GROUP GR1 USER-COMMAND XX. "생성
SELECTION-SCREEN COMMENT (20) FOR FIELD RB_CRT.

PARAMETERS RB_DISP RADIOBUTTON GROUP GR1 DEFAULT 'X'.    "조회/변경
SELECTION-SCREEN COMMENT (20) FOR FIELD RB_DISP.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK BL1.


SELECTION-SCREEN BEGIN OF BLOCK BL2 WITH FRAME TITLE TEXT-T02.
PARAMETERS: P_FILENM   TYPE RLGRAP-FILENAME DEFAULT 'C:W.xls' "파일경로
            OBLIGATORY MODIF ID A.
SELECTION-SCREEN END OF BLOCK BL2.


SELECTION-SCREEN BEGIN OF BLOCK BL3 WITH FRAME TITLE TEXT-T03.
SELECT-OPTIONS: S_VBUKR FOR PROJ-VBUKR NO INTERVALS MODIF ID B, "회사코드
                S_PSPID FOR PROJ-PSPID NO INTERVALS MODIF ID B, "프로젝트 코드
                S_POSID FOR PRPS-POSID NO INTERVALS MODIF ID B, "WBS 코드
                S_PRCTR FOR PROJ-PRCTR NO INTERVALS MODIF ID B, "손익센터
                S_ERDAT FOR PROJ-ERDAT NO-EXTENSION MODIF ID B. "생성일자
SELECTION-SCREEN END OF BLOCK BL3.
