*&---------------------------------------------------------------------*
*& Include          ZCOR0090SCR
*&---------------------------------------------------------------------*

SELECTION-SCREEN FUNCTION KEY 1.

*-- Source
SELECTION-SCREEN: BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-T01.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(12) TEXT-001 FOR FIELD PA_KOKRS.
SELECTION-SCREEN POSITION 33.
PARAMETERS: PA_KOKRS TYPE KOKRS MEMORY ID CAC OBLIGATORY
                                DEFAULT '1000'
                                MATCHCODE OBJECT CSH_TKA01.
SELECTION-SCREEN COMMENT 45(20) PA_KTXT MODIF ID MG1.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(12) TEXT-002 FOR FIELD PA_VERSN.
SELECTION-SCREEN POSITION 33.
PARAMETERS  PA_VERSN TYPE VERSN OBLIGATORY MATCHCODE
                                 OBJECT ZH_TKA09.
SELECTION-SCREEN COMMENT 45(20) PA_VTXT MODIF ID MG1.
SELECTION-SCREEN END OF LINE.

PARAMETERS  PA_GJAHR TYPE GJAHR DEFAULT SY-DATUM(4) OBLIGATORY.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(12) TEXT-003 FOR FIELD PA_SPERL.
SELECTION-SCREEN POSITION 33.
PARAMETERS : PA_SPERL TYPE PERBL OBLIGATORY DEFAULT '001'.

SELECTION-SCREEN COMMENT 45(12) TEXT-004 FOR FIELD PA_EPERL.
SELECTION-SCREEN POSITION 65.
PARAMETERS : PA_EPERL TYPE PERBL OBLIGATORY DEFAULT '012'.
SELECTION-SCREEN END OF LINE.

PARAMETERS  PA_BUKRS TYPE T001-BUKRS   OBLIGATORY.




SELECTION-SCREEN: END OF BLOCK B1.

*--- Target
SELECTION-SCREEN: BEGIN OF BLOCK B2 WITH FRAME TITLE TEXT-T02.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(12) TEXT-006 FOR FIELD PV_TVERS.
SELECTION-SCREEN POSITION 33.
PARAMETERS : PV_TVERS TYPE VERSN MATCHCODE
                                 OBJECT ZH_TKA09.

SELECTION-SCREEN COMMENT 45(12) TEXT-007 FOR FIELD PV_TVERE.
SELECTION-SCREEN POSITION 65.
PARAMETERS : PV_TVERE TYPE VERSN MATCHCODE
                                 OBJECT ZH_TKA09.

SELECTION-SCREEN END OF LINE.

PARAMETERS  P_TGJAHR TYPE GJAHR  DEFAULT SY-DATUM(4).

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(12) TEXT-003 FOR FIELD P_TSPERL.
SELECTION-SCREEN POSITION 33.
PARAMETERS : P_TSPERL TYPE PERBL OBLIGATORY DEFAULT '001'.

SELECTION-SCREEN COMMENT 45(12) TEXT-004 FOR FIELD P_TEPERL.
SELECTION-SCREEN POSITION 65.
PARAMETERS : P_TEPERL TYPE PERBL OBLIGATORY DEFAULT '012'.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN: END OF BLOCK B2.

*-- Target history
SELECTION-SCREEN: BEGIN OF BLOCK B3 WITH FRAME TITLE TEXT-T03.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(12) TEXT-002 FOR FIELD P_HVERSN
                                        MODIF ID MG1.
SELECTION-SCREEN POSITION 33.

PARAMETERS  P_HVERSN TYPE VERSN OBLIGATORY MATCHCODE
                                 OBJECT ZH_TKA09
                                 DEFAULT 'B1' MODIF ID MG1.
SELECTION-SCREEN COMMENT 45(20) P_HVTXT MODIF ID MG1.
SELECTION-SCREEN END OF LINE.

PARAMETERS  P_HGJAHR TYPE GJAHR  DEFAULT SY-DATUM(4) MODIF ID MG1.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(12) TEXT-003 FOR FIELD P_HSPERL
                               MODIF ID MG1.
SELECTION-SCREEN POSITION 33.
PARAMETERS : P_HSPERL TYPE PERBL OBLIGATORY DEFAULT '001'
                               MODIF ID MG1.

SELECTION-SCREEN COMMENT 45(12) TEXT-004 FOR FIELD P_HEPERL
                                MODIF ID MG1.
SELECTION-SCREEN POSITION 65.
PARAMETERS : P_HEPERL TYPE PERBL OBLIGATORY DEFAULT '012'
                                MODIF ID MG1.
SELECTION-SCREEN END OF LINE.

PARAMETERS PA_CHK AS CHECKBOX DEFAULT 'X' MODIF ID MG1.

SELECTION-SCREEN: END OF BLOCK B3.
