*&---------------------------------------------------------------------*
*& Include          ZCOR0010SCR
*&---------------------------------------------------------------------*

SELECTION-SCREEN FUNCTION KEY 1.
SELECTION-SCREEN FUNCTION KEY 2.

SELECTION-SCREEN: BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-T01.


SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(12) TEXT-005 FOR FIELD PA_KOKRS.
SELECTION-SCREEN POSITION 33.
PARAMETERS: PA_KOKRS TYPE KOKRS MEMORY ID CAC OBLIGATORY
                                MATCHCODE OBJECT CSH_TKA01.
SELECTION-SCREEN COMMENT 45(20) PA_KTXT MODIF ID MG1.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(12) TEXT-004 FOR FIELD PA_VERSN.
SELECTION-SCREEN POSITION 33.
PARAMETERS  PA_VERSN TYPE VERSN DEFAULT 'P1' OBLIGATORY MATCHCODE
                                 OBJECT ZH_TKA09.
SELECTION-SCREEN COMMENT 45(20) PA_VTXT MODIF ID MG1.
SELECTION-SCREEN END OF LINE.

PARAMETERS  PA_GJAHR TYPE GJAHR DEFAULT SY-DATUM(4) OBLIGATORY.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(12) TEXT-002 FOR FIELD PA_SPERL.
SELECTION-SCREEN POSITION 33.
PARAMETERS : PA_SPERL TYPE PERBL DEFAULT '1' OBLIGATORY.

SELECTION-SCREEN COMMENT 45(12) TEXT-003 FOR FIELD PA_EPERL.
SELECTION-SCREEN POSITION 65.
PARAMETERS : PA_EPERL TYPE PERBL DEFAULT '12' OBLIGATORY.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN SKIP 1.

PARAMETERS: PA_FILE TYPE RLGRAP-FILENAME OBLIGATORY DEFAULT 'C:\'.

SELECTION-SCREEN: END OF BLOCK B1.

SELECTION-SCREEN COMMENT 1(80) TEXT-008.
