*&---------------------------------------------------------------------*
*& Include          ZCOR0330SCR
*&---------------------------------------------------------------------*

SELECTION-SCREEN FUNCTION KEY 1.
SELECTION-SCREEN: BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-T01.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(12) TEXT-001 FOR FIELD PA_KOKRS.
SELECTION-SCREEN POSITION 33.
PARAMETERS: PA_KOKRS TYPE KOKRS OBLIGATORY
                                MATCHCODE OBJECT CSH_TKA01
                                DEFAULT '1000'
                                MODIF ID MG1.
SELECTION-SCREEN COMMENT 45(20) PA_KTXT MODIF ID MG1.
SELECTION-SCREEN END OF LINE.

SELECT-OPTIONS SO_ERDAT FOR ZCOT1190-ERDAT.
SELECT-OPTIONS SO_ERNAM FOR ZCOT1190-ERNAM OBLIGATORY
        MATCHCODE OBJECT SC_USER
        DEFAULT SY-UNAME
        MODIF ID MG2.
SELECT-OPTIONS SO_GWKEY FOR ZCOT1190-GWKEY.
SELECT-OPTIONS SO_GWTYP FOR ZCOT1190-GWTYP.
SELECT-OPTIONS SO_GWSTS FOR ZCOT1190-GWSTS DEFAULT 'I0'.

SELECTION-SCREEN: END OF BLOCK B1.
