*&---------------------------------------------------------------------*
*& Include          ZCOR0110SCR
*&---------------------------------------------------------------------*

SELECTION-SCREEN FUNCTION KEY 1.

SELECTION-SCREEN: BEGIN OF BLOCK b1 WITH FRAME TITLE TEXT-t01.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(12) TEXT-001 FOR FIELD pa_kokrs.
SELECTION-SCREEN POSITION 33.
PARAMETERS: pa_kokrs TYPE kokrs OBLIGATORY
                                MATCHCODE OBJECT csh_tka01
                                DEFAULT '1000'.
SELECTION-SCREEN COMMENT 45(20) pa_ktxt MODIF ID mg1.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(12) TEXT-002 FOR FIELD pa_versn.
SELECTION-SCREEN POSITION 33.
PARAMETERS  pa_versn TYPE versn OBLIGATORY MATCHCODE
                                 OBJECT zh_tka09
                                 DEFAULT 'B1'.
SELECTION-SCREEN COMMENT 45(20) pa_vtxt.
SELECTION-SCREEN END OF LINE.

PARAMETERS  pa_gjahr TYPE gjahr DEFAULT sy-datum(4) OBLIGATORY.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(12) TEXT-003 FOR FIELD pa_sperl .
SELECTION-SCREEN POSITION 33.
PARAMETERS : pa_sperl TYPE perbl DEFAULT '001' OBLIGATORY. " 20210617 BSGSM_FCM

SELECTION-SCREEN COMMENT 45(12) TEXT-004 FOR FIELD pa_eperl.
SELECTION-SCREEN POSITION 65.
PARAMETERS : pa_eperl TYPE perbl DEFAULT '012' OBLIGATORY. " 20210617 BSGSM_FCM
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN: END OF BLOCK b1.

SELECTION-SCREEN: BEGIN OF BLOCK b2 WITH FRAME TITLE TEXT-t02.

SELECTION-SCREEN BEGIN OF LINE.

PARAMETERS: pa_rad1 RADIOBUTTON GROUP rd1 DEFAULT 'X' USER-COMMAND us1.
SELECTION-SCREEN COMMENT 2(12) TEXT-005 FOR FIELD pa_rad1.


SELECTION-SCREEN POSITION 20.
PARAMETERS  pa_rad2 RADIOBUTTON GROUP rd1.

SELECTION-SCREEN COMMENT 23(12) TEXT-006 FOR FIELD pa_rad2.

SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN: BEGIN OF BLOCK b3 WITH FRAME.

SELECT-OPTIONS: so_kostl FOR csks-kostl MODIF ID kos
                                        MATCHCODE OBJECT kost.

PARAMETERS pa_ksgru TYPE ksgru MODIF ID kos.

SELECT-OPTIONS so_bukrs FOR prps-pbukr MODIF ID wbs.
SELECT-OPTIONS so_prctr FOR prps-prctr MODIF ID wbs.
SELECT-OPTIONS so_pspid FOR proj-pspid MODIF ID wbs.
SELECT-OPTIONS so_posid FOR prps-posid MODIF ID wbs
                                       MATCHCODE OBJECT prp.

PARAMETERS pa_pdgr TYPE posidgr MODIF ID wbs.

SELECTION-SCREEN SKIP 1.

SELECT-OPTIONS: so_kstar FOR cska-kstar  MATCHCODE
                                  OBJECT reexcocostelem.

PARAMETERS pa_kagru TYPE kagru.

SELECTION-SCREEN: END OF BLOCK b3.

PARAMETERS pa_check AS CHECKBOX.

SELECTION-SCREEN: END OF BLOCK b2.

SELECTION-SCREEN COMMENT 1(80) TEXT-010.
