*&---------------------------------------------------------------------*
*& Include          ZCOR0040MBSCR
*&---------------------------------------------------------------------*
SELECTION-SCREEN FUNCTION KEY 1.
SELECTION-SCREEN: BEGIN OF BLOCK bc1 WITH FRAME TITLE TEXT-b01.

PARAMETER : pa_back TYPE c RADIOBUTTON GROUP r2 DEFAULT 'X' USER-COMMAND rdo MODIF ID CC.
PARAMETER : pa_rest TYPE c RADIOBUTTON GROUP r2.
PARAMETER : pa_crea TYPE c RADIOBUTTON GROUP r2 .
PARAMETER : pa_dele TYPE c RADIOBUTTON GROUP r2.
PARAMETER : pa_1100  TYPE c RADIOBUTTON GROUP r2.

SELECTION-SCREEN: END OF BLOCK bc1.


SELECTION-SCREEN: BEGIN OF BLOCK bc2  .

 SELECT-OPTIONS : SO_BUKRS  FOR ZCOT0010-BUKRS MODIF ID KK.
 PARAMETERS :  pa_gjahr   type zcot0010-gjahr DEFAULT '2021' MODIF ID KK..



SELECTION-SCREEN: END OF BLOCK bc2.
