*&---------------------------------------------------------------------*
*& Include          ZCOR0440SCR
*&---------------------------------------------------------------------*

SELECTION-SCREEN FUNCTION KEY 1.
SELECTION-SCREEN: BEGIN OF BLOCK BL1 WITH FRAME TITLE TEXT-T01.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(12) TEXT-002 FOR FIELD PA_VERSN.
SELECTION-SCREEN POSITION 33.
PARAMETERS  PA_VERSN TYPE VERSN OBLIGATORY MATCHCODE
                                 OBJECT ZH_TKA09
                                 DEFAULT 'B1'
                                 MODIF ID MG1.
SELECTION-SCREEN COMMENT 45(20) PA_VTXT MODIF ID MG1.
SELECTION-SCREEN END OF LINE.

PARAMETERS PA_GJAHR TYPE GJAHR OBLIGATORY DEFAULT SY-DATUM(4).

PARAMETERS PA_BUKRS TYPE BUKRS OBLIGATORY DEFAULT '1100'.

PARAMETERS PA_PDGR TYPE POSIDGR NO-DISPLAY.

SELECT-OPTIONS SO_PSPID FOR PROJ-PSPID MATCHCODE OBJECT PRS.
SELECT-OPTIONS SO_POSID FOR PRPS-POSID MATCHCODE OBJECT PRP.

SELECTION-SCREEN: END OF BLOCK BL1.
