*&---------------------------------------------------------------------*
*& Include          ZCOR0240SCR
*&---------------------------------------------------------------------*
SELECTION-SCREEN: BEGIN OF BLOCK BL1 WITH FRAME TITLE TEXT-T01.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(12) TEXT-001 FOR FIELD PA_KOKRS.
SELECTION-SCREEN POSITION 33.
PARAMETERS: PA_KOKRS TYPE KOKRS MEMORY ID CAC OBLIGATORY
                                MATCHCODE OBJECT CSH_TKA01
                                MODIF ID MG1 DEFAULT '1000'.
SELECTION-SCREEN COMMENT 45(20) PA_KTXT MODIF ID MG1.
SELECTION-SCREEN END OF LINE.

PARAMETERS: PA_GJAHR TYPE GJAHR OBLIGATORY DEFAULT SY-DATUM(4),
            PA_VERSN TYPE VERSN OBLIGATORY DEFAULT '0',
            PA_PRCTR TYPE PRCTR MEMORY ID PRC,
            PA_BUKRS TYPE BUKRS MEMORY ID BUK.

SELECT-OPTIONS: SO_POSID FOR PRPS-POSID MODIF ID WBS
                                        MATCHCODE OBJECT ZZ_PRPMP.

PARAMETERS: PA_PDGR TYPE POSIDGR MODIF ID WBS.
SELECTION-SCREEN: END OF BLOCK BL1.

"__ help
SELECTION-SCREEN FUNCTION KEY 1.
