*&---------------------------------------------------------------------*
*& Include          ZCOR0130SCR
*&---------------------------------------------------------------------*

*SELECTION-SCREEN: BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-T01.
*SELECTION-SCREEN BEGIN OF LINE.
*
*PARAMETERS: PA_RAD1 RADIOBUTTON GROUP RD1 DEFAULT 'X'.
*SELECTION-SCREEN COMMENT 2(12) TEXT-001 FOR FIELD PA_RAD1.
*SELECTION-SCREEN POSITION 20.
*PARAMETERS  PA_RAD2 RADIOBUTTON GROUP RD1.
*SELECTION-SCREEN COMMENT 25(12) TEXT-002 FOR FIELD PA_RAD2.
*
*SELECTION-SCREEN END OF LINE.
*SELECTION-SCREEN: END OF BLOCK B1.


SELECTION-SCREEN: BEGIN OF BLOCK B2 WITH FRAME TITLE TEXT-T02.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN POSITION 30.
PARAMETERS: PA_WW010 RADIOBUTTON GROUP RD2 DEFAULT 'X'.
SELECTION-SCREEN COMMENT 4(12) TEXT-R01 FOR FIELD PA_WW010.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN POSITION 30.
PARAMETERS: PA_WW020 RADIOBUTTON GROUP RD2.
SELECTION-SCREEN COMMENT 4(12) TEXT-R02 FOR FIELD PA_WW020.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN POSITION 30.
PARAMETERS: PA_WW030 RADIOBUTTON GROUP RD2.
SELECTION-SCREEN COMMENT 4(12) TEXT-R03 FOR FIELD PA_WW030.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN POSITION 30.
PARAMETERS: PA_WW040 RADIOBUTTON GROUP RD2.
SELECTION-SCREEN COMMENT 4(12) TEXT-R04 FOR FIELD PA_WW040.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN POSITION 30.
PARAMETERS: PA_WW050 RADIOBUTTON GROUP RD2.
SELECTION-SCREEN COMMENT 4(12) TEXT-R05 FOR FIELD PA_WW050.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN POSITION 30.
PARAMETERS: PA_WW060 RADIOBUTTON GROUP RD2.
SELECTION-SCREEN COMMENT 4(12) TEXT-R06 FOR FIELD PA_WW060.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN POSITION 30.
PARAMETERS: PA_WW070 RADIOBUTTON GROUP RD2.
SELECTION-SCREEN COMMENT 4(12) TEXT-R07 FOR FIELD PA_WW070.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN POSITION 30.
PARAMETERS: PA_WW080 RADIOBUTTON GROUP RD2.
SELECTION-SCREEN COMMENT 4(12) TEXT-R08 FOR FIELD PA_WW080.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN POSITION 30.
PARAMETERS: PA_WW090 RADIOBUTTON GROUP RD2.
SELECTION-SCREEN COMMENT 4(12) TEXT-R09 FOR FIELD PA_WW090.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN POSITION 30.
PARAMETERS: PA_WW100 RADIOBUTTON GROUP RD2.
SELECTION-SCREEN COMMENT 4(12) TEXT-R10 FOR FIELD PA_WW100.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN POSITION 30.
PARAMETERS: PA_WW110 RADIOBUTTON GROUP RD2.
SELECTION-SCREEN COMMENT 4(12) TEXT-R11 FOR FIELD PA_WW110.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN POSITION 30.
PARAMETERS: PA_WW120 RADIOBUTTON GROUP RD2.
SELECTION-SCREEN COMMENT 4(12) TEXT-R12 FOR FIELD PA_WW120.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN: END OF BLOCK B2.

"__ help
SELECTION-SCREEN FUNCTION KEY 1.
