*&---------------------------------------------------------------------*
*& Include          ZCOR0590SCR
*&---------------------------------------------------------------------*

SELECTION-SCREEN FUNCTION KEY 1.
SELECTION-SCREEN FUNCTION KEY 2.
*SELECTION-SCREEN FUNCTION KEY 3.

SELECTION-SCREEN BEGIN OF BLOCK B01 WITH FRAME TITLE TEXT_S01.

PARAMETERS     P_KOKRS TYPE TKA01-KOKRS OBLIGATORY.
SELECT-OPTIONS S_CYCLE FOR  GV_CYCLE.

SELECTION-SCREEN END OF BLOCK B01.

SELECTION-SCREEN BEGIN OF BLOCK B03 WITH FRAME TITLE TEXT_S03.

PARAMETERS P_ACT    RADIOBUTTON GROUP RG2 DEFAULT 'X'.
PARAMETERS P_PLN    RADIOBUTTON GROUP RG2.

SELECTION-SCREEN END OF BLOCK B03.
