*&---------------------------------------------------------------------*
*& Include          ZCOR0040SCR
*&---------------------------------------------------------------------*

SELECTION-SCREEN FUNCTION KEY 1.

SELECTION-SCREEN: BEGIN OF BLOCK bl1 WITH FRAME TITLE TEXT-t01.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(12) TEXT-001 FOR FIELD pa_kokrs.
SELECTION-SCREEN POSITION 33.
PARAMETERS: pa_kokrs TYPE kokrs MEMORY ID cac OBLIGATORY
                                MATCHCODE OBJECT csh_tka01.
SELECTION-SCREEN COMMENT 45(20) pa_ktxt MODIF ID mg1.
SELECTION-SCREEN END OF LINE.


SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(12) TEXT-011 FOR FIELD pa_bukrs.
SELECTION-SCREEN POSITION 33.
PARAMETERS: pa_bukrs TYPE bukrs MEMORY ID buk OBLIGATORY.

SELECTION-SCREEN COMMENT 45(20) pa_butxt MODIF ID mg1.

SELECTION-SCREEN END OF LINE.


PARAMETERS pa_gjahr TYPE gjahr OBLIGATORY DEFAULT sy-datum(4).

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(12) TEXT-002 FOR FIELD pa_kokrs.
SELECTION-SCREEN POSITION 33.
PARAMETERS pa_ctype TYPE zectype MEMORY ID cty OBLIGATORY
                                 MATCHCODE OBJECT zh_ctype.
SELECTION-SCREEN COMMENT 45(20) pa_ctxt.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN: END OF BLOCK bl1.
