*&---------------------------------------------------------------------*
*& Include          ZCOR0280SCR
*&---------------------------------------------------------------------*
SELECTION-SCREEN: BEGIN OF BLOCK bl1 WITH FRAME TITLE TEXT-t01.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(12) TEXT-001 FOR FIELD pa_kokrs.
SELECTION-SCREEN POSITION 33.
PARAMETERS: pa_kokrs TYPE kokrs MEMORY ID cac OBLIGATORY
                                MATCHCODE OBJECT csh_tka01
                                MODIF ID mg1 DEFAULT '1000'.
SELECTION-SCREEN COMMENT 45(20) pa_ktxt MODIF ID mg1.
SELECTION-SCREEN END OF LINE.

PARAMETERS: pa_gjahr TYPE gjahr OBLIGATORY DEFAULT sy-datum(4),
            pa_versn TYPE versn OBLIGATORY DEFAULT 'P1'
                                MATCHCODE OBJECT zh_tka09.


SELECT-OPTIONS: so_bukrs  FOR prps-pbukr NO INTERVALS.  "add bsgsm_fcm 2021

SELECT-OPTIONS: so_posid FOR prps-posid MODIF ID wbs
                                       MATCHCODE OBJECT prp.

PARAMETERS: pa_pdgr TYPE posidgr MODIF ID wbs.
SELECTION-SCREEN: END OF BLOCK bl1.

SELECTION-SCREEN: BEGIN OF BLOCK b2 WITH FRAME TITLE TEXT-t02.

SELECTION-SCREEN BEGIN OF LINE.

PARAMETERS: pa_rad1 RADIOBUTTON GROUP rd1 DEFAULT 'X' USER-COMMAND us1.
SELECTION-SCREEN COMMENT 2(12) TEXT-002 FOR FIELD pa_rad1.


SELECTION-SCREEN POSITION 20.
PARAMETERS  pa_rad2 RADIOBUTTON GROUP rd1.

SELECTION-SCREEN COMMENT 23(12) TEXT-003 FOR FIELD pa_rad2.

SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN: END OF BLOCK b2.

SELECTION-SCREEN COMMENT 1(80) TEXT-007.
SELECTION-SCREEN SKIP.
SELECTION-SCREEN COMMENT 1(80) TEXT-008.

"__ help
SELECTION-SCREEN FUNCTION KEY 1.
