*&---------------------------------------------------------------------*
*& Include          ZCOR0040SCR
*&---------------------------------------------------------------------*

SELECTION-SCREEN FUNCTION KEY 1.

SELECTION-SCREEN: BEGIN OF BLOCK BL1 WITH FRAME TITLE TEXT-T01.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(12) TEXT-001 FOR FIELD PA_KOKRS.
SELECTION-SCREEN POSITION 33.
PARAMETERS: PA_KOKRS TYPE KOKRS MEMORY ID CAC OBLIGATORY
                                MATCHCODE OBJECT CSH_TKA01.
SELECTION-SCREEN COMMENT 45(20) PA_KTXT MODIF ID MG1.
SELECTION-SCREEN END OF LINE.

PARAMETERS PA_GJAHR TYPE GJAHR OBLIGATORY DEFAULT SY-DATUM(4).

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(12) TEXT-002 FOR FIELD PA_KOKRS.
SELECTION-SCREEN POSITION 33.
PARAMETERS PA_CTYPE TYPE ZECTYPE MEMORY ID CTY OBLIGATORY
                                 MATCHCODE OBJECT ZH_CTYPE.
SELECTION-SCREEN COMMENT 45(20) PA_CTXT.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN: END OF BLOCK BL1.
