*&---------------------------------------------------------------------*
*& Include          ZCOR0460TO2
*&---------------------------------------------------------------------*


DATA: LS_TOOLBAR TYPE STB_BUTTON.

TYPES: BEGIN OF TY_LAYOUT,
         REPID    TYPE SYREPID,
         RESTRICT TYPE SALV_DE_LAYOUT_RESTRICTION,
         DEFAULT  TYPE SAP_BOOL,
         LAYOUT   TYPE DISVARIANT-VARIANT,
       END OF TY_LAYOUT.

DATA: GO_ALV        TYPE REF TO CL_SALV_TABLE,
      GO_FUNCTIONS  TYPE REF TO CL_SALV_FUNCTIONS_LIST,
      GO_LAYOUT     TYPE REF TO CL_SALV_LAYOUT,
      GO_DSPSET     TYPE REF TO CL_SALV_DISPLAY_SETTINGS,
      GO_SELECT     TYPE REF TO CL_SALV_SELECTIONS,
      GS_KEY        TYPE SALV_S_LAYOUT_KEY,

      GT_COLUMN_REF TYPE SALV_T_COLUMN_REF.

DATA GS_COLOR_ALV  TYPE LVC_S_COLO.
DATA GR_COLUMN TYPE REF TO CL_SALV_COLUMN_TABLE.

DATA: GT_ROWS_SALV TYPE SALV_T_ROW,
      GS_ROW_SALV  TYPE INT4.  "ALV position 기억

DATA: GV_COLUMN_TEXT TYPE STRING,
      GV_SCRTEXT_S   TYPE SCRTEXT_S,
      GV_SCRTEXT_M   TYPE SCRTEXT_M,
      GV_SCRTEXT_L   TYPE SCRTEXT_L.

DATA: GS_SALV_LAYOUT TYPE TY_LAYOUT.
DATA  GV_REPID TYPE SYREPID.

DEFINE _STYLE_DISABLED.
  GS_STYLE-FIELDNAME = &1.
  GS_STYLE-STYLE     = CL_GUI_ALV_GRID=>MC_STYLE_DISABLED.
  INSERT GS_STYLE INTO TABLE GT_STYLE.
END-OF-DEFINITION.

DEFINE _STYLE_ENABLED.
  GS_STYLE-FIELDNAME = &1.
  GS_STYLE-STYLE     = CL_GUI_ALV_GRID=>MC_STYLE_ENABLED.
  INSERT GS_STYLE INTO TABLE GT_STYLE.
END-OF-DEFINITION.
