*&---------------------------------------------------------------------*
*& Include          ZCOR0390SCR
*&---------------------------------------------------------------------*
SELECTION-SCREEN: BEGIN OF BLOCK BL1 WITH FRAME TITLE TEXT-T01.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(12) TEXT-001 FOR FIELD PA_KOKRS.
SELECTION-SCREEN POSITION 33.
PARAMETERS: PA_KOKRS TYPE KOKRS MEMORY ID CAC OBLIGATORY
                                MATCHCODE OBJECT CSH_TKA01
                                MODIF ID MG1 DEFAULT '1000'.
SELECTION-SCREEN COMMENT 45(20) PA_KTXT MODIF ID MG1.
SELECTION-SCREEN END OF LINE.



SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(12) TEXT-K03 FOR FIELD PA_GJAHR.
SELECTION-SCREEN POSITION 33.
PARAMETERS  PA_GJAHR TYPE GJAHR DEFAULT SY-DATUM(4) OBLIGATORY
                                MODIF ID G1.
*
SELECTION-SCREEN COMMENT 40(6) TEXT-K04 FOR FIELD PA_PERBL.
SELECTION-SCREEN POSITION 47.
PARAMETERS : PA_PERBL TYPE PERBL DEFAULT '001' OBLIGATORY.

SELECTION-SCREEN COMMENT 53(6) TEXT-K05 FOR FIELD PA_EPERL.
SELECTION-SCREEN POSITION 60.
PARAMETERS : PA_EPERL TYPE PERBL DEFAULT '012' OBLIGATORY.
SELECTION-SCREEN END OF LINE.


PARAMETERS : PA_VERSN TYPE VERSN OBLIGATORY DEFAULT '000'
                                MATCHCODE OBJECT ZH_TKA09.



***PARAMETERS: PA_GJAHR TYPE GJAHR OBLIGATORY DEFAULT SY-DATUM(4),
***            PA_PERBL TYPE PERBL OBLIGATORY DEFAULT SY-DATUM+4(2),
***            PA_VERSN TYPE VERSN OBLIGATORY DEFAULT '000'
***                                MATCHCODE OBJECT ZH_TKA09.



SELECTION-SCREEN: END OF BLOCK BL1.

SELECTION-SCREEN: BEGIN OF BLOCK BL2 WITH FRAME TITLE TEXT-T02.
*PARAMETERS: PA_BUKRS TYPE BUKRS OBLIGATORY MEMORY ID BUK.
SELECT-OPTIONS: SO_BUKRS FOR T001-BUKRS NO-EXTENSION NO INTERVALS.

SELECT-OPTIONS: SO_POSID FOR PRPS-POSID MODIF ID WBS
                                       MATCHCODE OBJECT PRP.

PARAMETERS: PA_PDGR TYPE POSIDGR MODIF ID WBS.

*--------------------------------------------------------------------*
* [ESG_CO] DEV_ESG 기존PGM 고도화 #3, 2021.11.24 13:56:44, MDP_06
*--------------------------------------------------------------------*
SELECTION-SCREEN SKIP.
PARAMETERS PA_EQWBS AS CHECKBOX.

SELECTION-SCREEN: END OF BLOCK BL2.

"__ help
SELECTION-SCREEN FUNCTION KEY 1.
