*&---------------------------------------------------------------------*
*& Include          ZCOR0300SCR
*&---------------------------------------------------------------------*

SELECTION-SCREEN FUNCTION KEY 1.
SELECTION-SCREEN: BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-T01.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(12) TEXT-001 FOR FIELD PA_KOKRS.
SELECTION-SCREEN POSITION 33.
PARAMETERS: PA_KOKRS TYPE KOKRS OBLIGATORY
                                MATCHCODE OBJECT CSH_TKA01
                                DEFAULT '1000'
                                MODIF ID MG1.
SELECTION-SCREEN COMMENT 45(20) PA_KTXT MODIF ID MG1.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(12) TEXT-002 FOR FIELD PA_VERSN
                                        MODIF ID MG1.
SELECTION-SCREEN POSITION 33.
PARAMETERS  PA_VERSN TYPE VERSN OBLIGATORY MATCHCODE
                                 OBJECT ZH_TKA09
                                 DEFAULT '000'
                                 MODIF ID MG1.
SELECTION-SCREEN COMMENT 45(20) PA_VTXT.
SELECTION-SCREEN END OF LINE.

PARAMETERS PA_GJAHR TYPE GJAHR DEFAULT SY-DATUM(4) OBLIGATORY.
PARAMETERS PA_SPERL TYPE PERBL OBLIGATORY.

SELECT-OPTIONS SO_BUKRS FOR T001-BUKRS NO-EXTENSION NO INTERVALS.
SELECTION-SCREEN: END OF BLOCK B1.
