*&---------------------------------------------------------------------*
*& Include          ZCOR0110SCR
*&---------------------------------------------------------------------*
SELECTION-SCREEN FUNCTION KEY 1.
SELECTION-SCREEN: BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-T01.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(12) TEXT-001 FOR FIELD PA_KOKRS.
SELECTION-SCREEN POSITION 33.
PARAMETERS: PA_KOKRS TYPE KOKRS OBLIGATORY
                                MATCHCODE OBJECT CSH_TKA01
                                DEFAULT '1000'.
SELECTION-SCREEN COMMENT 45(20) PA_KTXT MODIF ID MG1.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(12) TEXT-002 FOR FIELD PA_VERSN.
SELECTION-SCREEN POSITION 33.
PARAMETERS  PA_VERSN TYPE VERSN OBLIGATORY MATCHCODE
                                 OBJECT ZH_TKA09
                                 DEFAULT 'B1'.
SELECTION-SCREEN COMMENT 45(20) PA_VTXT.
SELECTION-SCREEN END OF LINE.

PARAMETERS  PA_GJAHR TYPE GJAHR DEFAULT SY-DATUM(4) OBLIGATORY.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(12) TEXT-003 FOR FIELD PA_SPERL.
SELECTION-SCREEN POSITION 33.
PARAMETERS : PA_SPERL TYPE PERBL OBLIGATORY DEFAULT '001'.

SELECTION-SCREEN COMMENT 45(12) TEXT-004 FOR FIELD PA_EPERL.
SELECTION-SCREEN POSITION 65.
PARAMETERS : PA_EPERL TYPE PERBL OBLIGATORY DEFAULT '012'.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN: END OF BLOCK B1.

SELECTION-SCREEN: BEGIN OF BLOCK B2 WITH FRAME TITLE TEXT-T02.

SELECTION-SCREEN BEGIN OF LINE.

PARAMETERS: PA_RAD1 RADIOBUTTON GROUP RD1 DEFAULT 'X' USER-COMMAND US1.
SELECTION-SCREEN COMMENT 2(12) TEXT-005 FOR FIELD PA_RAD1.


SELECTION-SCREEN POSITION 20.
PARAMETERS  PA_RAD2 RADIOBUTTON GROUP RD1.

SELECTION-SCREEN COMMENT 23(12) TEXT-006 FOR FIELD PA_RAD2.

SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN: BEGIN OF BLOCK B3 WITH FRAME.

SELECT-OPTIONS: SO_KOSTL FOR CSKS-KOSTL MODIF ID KOS
                                        MATCHCODE OBJECT KOST.

PARAMETERS PA_KSGRU TYPE KSGRU MODIF ID KOS.

SELECT-OPTIONS SO_BUKRS FOR PRPS-PBUKR MODIF ID WBS.
SELECT-OPTIONS SO_PRCTR FOR PRPS-PRCTR MODIF ID WBS.
SELECT-OPTIONS SO_PSPID FOR PROJ-PSPID MODIF ID WBS.
SELECT-OPTIONS SO_POSID FOR PRPS-POSID MODIF ID WBS
                                       MATCHCODE OBJECT PRP.

PARAMETERS PA_PDGR TYPE POSIDGR MODIF ID WBS.

SELECTION-SCREEN SKIP 1.

SELECT-OPTIONS: SO_KSTAR FOR CSKA-KSTAR  MATCHCODE
                                  OBJECT REEXCOCOSTELEM.

PARAMETERS PA_KAGRU TYPE KAGRU.

SELECTION-SCREEN: END OF BLOCK B3.

SELECTION-SCREEN: END OF BLOCK B2.
