*&---------------------------------------------------------------------*
*& Include          ZCOR0400SCR
*&---------------------------------------------------------------------*
SELECTION-SCREEN FUNCTION KEY 1.
SELECTION-SCREEN: BEGIN OF BLOCK BL1 WITH FRAME TITLE TEXT-T01.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(12) TEXT-001 FOR FIELD PA_KOKRS.
SELECTION-SCREEN POSITION 33.
PARAMETERS: PA_KOKRS TYPE KOKRS MEMORY ID CAC OBLIGATORY
                                MATCHCODE OBJECT CSH_TKA01
                                MODIF ID MG1 DEFAULT '1000'.
SELECTION-SCREEN COMMENT 45(20) PA_KTXT MODIF ID MG1.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(12) TEXT-002 FOR FIELD PA_VERSN.
SELECTION-SCREEN POSITION 33.
PARAMETERS  PA_VERSN TYPE VERSN OBLIGATORY MATCHCODE
                                 OBJECT ZH_TKA09
                                 DEFAULT 'B1'
                                 MODIF ID MG1.
SELECTION-SCREEN COMMENT 45(20) PA_VTXT MODIF ID MG1.
SELECTION-SCREEN END OF LINE.

PARAMETERS PA_GJAHR TYPE GJAHR OBLIGATORY DEFAULT SY-DATUM(4).

SELECTION-SCREEN: END OF BLOCK BL1.

SELECTION-SCREEN: BEGIN OF BLOCK BL2 WITH FRAME TITLE TEXT-T02.


SELECTION-SCREEN BEGIN OF LINE.

PARAMETERS: PA_RAD1 RADIOBUTTON GROUP RD1 DEFAULT 'X' USER-COMMAND US1.
SELECTION-SCREEN COMMENT 2(12) TEXT-003 FOR FIELD PA_RAD1.


SELECTION-SCREEN POSITION 20.
PARAMETERS  PA_RAD2 RADIOBUTTON GROUP RD1.

SELECTION-SCREEN COMMENT 23(12) TEXT-004 FOR FIELD PA_RAD2.

SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN: BEGIN OF BLOCK BL3 WITH FRAME.

PARAMETERS PA_KOSTL TYPE KOSTL  MODIF ID KOS MATCHCODE OBJECT KOST.
PARAMETERS PA_POSID TYPE PS_POSID MODIF ID WBS MATCHCODE OBJECT PRP.

SELECTION-SCREEN: END OF BLOCK BL3.

SELECTION-SCREEN: END OF BLOCK BL2.
