*&---------------------------------------------------------------------*
*& Include          ZCOR0420NT01
*&---------------------------------------------------------------------*
REPORT ZCOR0420N MESSAGE-ID ZCO01.

TABLES: AFRU, COBK, AFVC, T430, BKPF, S001.

*  ALV + CONTATINER
CLASS : LCL_ALV_GRID        DEFINITION DEFERRED,
        LCL_EVENT_RECEIVER  DEFINITION DEFERRED.

DATA: G_EVENT_RECEIVER  TYPE REF TO LCL_EVENT_RECEIVER,
      G_GRID            TYPE REF TO CL_GUI_ALV_GRID.

* ALV COMPOSITION
DATA : GS_VARIANT   LIKE DISVARIANT,
       GS_LAYOUT    TYPE LVC_S_LAYO,
       GV_SCROLL    TYPE LVC_S_STBL,
       GS_FCAT      TYPE LVC_S_FCAT,
       GT_FIELDCAT  TYPE LVC_T_FCAT,
       GT_ROWS      TYPE LVC_T_ROW WITH HEADER LINE,
       G_POS        TYPE I.

* The Declaration of Variables
DATA: GT_EXCLUDE    TYPE UI_FUNCTIONS.

DATA: BEGIN OF GT_COBK OCCURS 0,
        KOKRS LIKE COBK-KOKRS,
        BELNR LIKE COBK-BELNR, "CO전표
        BUDAT LIKE COBK-BUDAT,
        REFBN LIKE COBK-REFBN,
        AWKEY LIKE COBK-AWKEY,
        AWORG LIKE COBK-AWORG,
        PSPNR LIKE COEP-PSPNR,
      END OF GT_COBK.

DATA: BEGIN OF GT_BKPF OCCURS 0,
        BELNR LIKE BKPF-BELNR,
        BUKRS LIKE BKPF-BUKRS,
        BUDAT LIKE BKPF-BUDAT,
        BLART LIKE BKPF-BLART,
        BSTAT LIKE BKPF-BSTAT,  "전표상태
        AWKEY LIKE BKPF-AWKEY,
        GJAHR LIKE BKPF-GJAHR,
      END OF GT_BKPF.

      DATA: BEGIN OF GT_BKPF1 OCCURS 0,
        BELNR LIKE BKPF-BELNR,
           END OF GT_BKPF1.

DATA : BEGIN OF GT_LIST OCCURS 0,
         CHECK,
         ICON    LIKE ICON-ID,
         BUKRS   LIKE BKPF-BUKRS,
         BELNR   LIKE BKPF-BELNR,
         BUDAT   LIKE BKPF-BUDAT,
         BLART   LIKE BKPF-BLART,
         BSTAT   LIKE BKPF-BSTAT,
         BELNR2  LIKE COBK-BELNR,
         PSPNR  LIKE COEP-PSPNR,
         XBILK   LIKE SKA1-XBILK,
         AWORG   LIKE COBK-AWORG,
         GJAHR   LIKE BKPF-GJAHR,
         CELLTAB TYPE LVC_T_STYL,
       END OF GT_LIST.

DATA : GV_ERROR, GV_TEST,
       GV_CNT(3) TYPE I.

RANGES : GR_DATE FOR BKPF-BUDAT.
*----------------------------------------------------------------------*
* SELECTION-SCREEN.
*----------------------------------------------------------------------*
SELECTION-SCREEN BEGIN OF BLOCK B01 WITH FRAME TITLE TEXT-T01.
PARAMETERS    : P_KOKRS LIKE CCSS-KOKRS MEMORY ID CAC OBLIGATORY.
*                P_BUKRS LIKE BKPF-BUKRS OBLIGATORY,
*                P_SPMON TYPE SPMON OBLIGATORY.

SELECT-OPTIONS: S_BUKRS  FOR BKPF-BUKRS," OBLIGATORY,
                s_spmon  FOR S001-SPMON OBLIGATORY NO-EXTENSION,
                S_BELNR  FOR COBK-BELNR,
                S_BELNR2 FOR BKPF-BELNR.
SELECTION-SCREEN   END OF BLOCK B01.
