*&---------------------------------------------------------------------*
*& Include          ZCOR0310SCR
*&---------------------------------------------------------------------*
SELECTION-SCREEN FUNCTION KEY 1.
SELECTION-SCREEN FUNCTION KEY 2.

SELECTION-SCREEN: BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-T01.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(12) TEXT-005 FOR FIELD PA_KOKRS.
SELECTION-SCREEN POSITION 33.
PARAMETERS: PA_KOKRS TYPE KOKRS MEMORY ID CAC OBLIGATORY
                                MATCHCODE OBJECT CSH_TKA01
                                MODIF ID MG1.
SELECTION-SCREEN COMMENT 45(20) PA_KTXT.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(12) TEXT-004 FOR FIELD PA_VERSN.
SELECTION-SCREEN POSITION 33.
PARAMETERS  PA_VERSN TYPE VERSN DEFAULT '000' OBLIGATORY MATCHCODE
                                 OBJECT ZH_TKA09 MODIF ID MG1.
SELECTION-SCREEN COMMENT 45(20) PA_VTXT .
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(12) TEXT-003 FOR FIELD PA_BUKRS.
SELECTION-SCREEN POSITION 33.
PARAMETERS  PA_BUKRS TYPE BUKRS  OBLIGATORY.
SELECTION-SCREEN COMMENT 45(20) PA_BTXT.
SELECTION-SCREEN END OF LINE.

PARAMETERS  PA_GJAHR TYPE GJAHR DEFAULT SY-DATUM(4) OBLIGATORY.

SELECTION-SCREEN SKIP 1.

PARAMETERS: PA_FILE TYPE RLGRAP-FILENAME OBLIGATORY DEFAULT 'C:\'.

SELECTION-SCREEN: END OF BLOCK B1.

SELECTION-SCREEN COMMENT 1(80) TEXT-006.
