*&---------------------------------------------------------------------*
*& Include          ZXCN1U22
*&---------------------------------------------------------------------*

 CNCI_PRPS_EXP-ZZSCT = ZCOS0020-ZZSCT.
 CNCI_PRPS_EXP-ZZPHA = ZCOS0020-ZZPHA.
 CNCI_PRPS_EXP-ZZWBT = ZCOS0020-ZZWBT.
 CNCI_PRPS_EXP-ZZBGU = ZCOS0020-ZZBGU.
 CNCI_PRPS_EXP-ZZBGD = ZCOS0020-ZZBGD.
 CNCI_PRPS_EXP-ZZPRG = ZCOS0020-ZZPRG.
 CNCI_PRPS_EXP-ZZADT = ZCOS0020-ZZADT.
 CNCI_PRPS_EXP-ZZHWB = ZCOS0020-ZZHWB.
 CNCI_PRPS_EXP-ZZBAG = ZCOS0020-ZZBAG.
 CNCI_PRPS_EXP-ZZIVC = ZCOS0020-ZZIVC.
 CNCI_PRPS_EXP-ZZCYP = ZCOS0020-ZZCYP.
 CNCI_PRPS_EXP-ZZCOP = ZCOS0020-ZZCOP.
