*&---------------------------------------------------------------------*
*& Include          ZXCN1U21
*&---------------------------------------------------------------------*

 CLEAR ZCOS0020.
 CLEAR GV_DISPLAY.

 ZCOS0020-ZZSCT = SAP_PRPS_IMP-ZZSCT.
 ZCOS0020-ZZPHA = SAP_PRPS_IMP-ZZPHA.
 ZCOS0020-ZZWBT = SAP_PRPS_IMP-ZZWBT.
 ZCOS0020-ZZBGU = SAP_PRPS_IMP-ZZBGU.
 ZCOS0020-ZZBGD = SAP_PRPS_IMP-ZZBGD.
 ZCOS0020-ZZPRG = SAP_PRPS_IMP-ZZPRG.
 ZCOS0020-ZZADT = SAP_PRPS_IMP-ZZADT.
 ZCOS0020-ZZHWB = SAP_PRPS_IMP-ZZHWB.
 ZCOS0020-ZZBAG = SAP_PRPS_IMP-ZZBAG.
 ZCOS0020-ZZIVC = SAP_PRPS_IMP-ZZIVC.
 ZCOS0020-ZZCYP = SAP_PRPS_IMP-ZZCYP.
 ZCOS0020-ZZCOP = SAP_PRPS_IMP-ZZCOP.

 GV_DISPLAY     = SAP_DISPLAY_ONLY.

*-- 매출 유형내역
 SELECT SINGLE ZZSCTTX INTO @ZCOS0020-ZZSCTTX
   FROM ZCOT1010T
  WHERE ZZSCT = @ZCOS0020-ZZSCT
    AND SPRAS = @SY-LANGU.

*-- 프로젝트 단계내역
 SELECT SINGLE ZZPHATX INTO @ZCOS0020-ZZPHATX
   FROM ZCOT1020T
  WHERE ZZPHA = @ZCOS0020-ZZPHA
    AND SPRAS = @SY-LANGU.

*-- WBS 유형내역
 SELECT SINGLE ZZWBTTX INTO @ZCOS0020-ZZWBTTX
   FROM ZCOT1030T
  WHERE ZZWBT = @ZCOS0020-ZZWBT
    AND SPRAS = @SY-LANGU.

*-- 사업구분내역
 SELECT SINGLE ZZBGUTX INTO @ZCOS0020-ZZBGUTX
   FROM ZCOT1040T
  WHERE ZZBGU = @ZCOS0020-ZZBGU
    AND SPRAS = @SY-LANGU.

*-- 사업구분상세내역
 SELECT SINGLE ZZBGDTX INTO @ZCOS0020-ZZBGDTX
   FROM ZCOT1050T
  WHERE ZZBGU = @ZCOS0020-ZZBGU
    AND ZZBGD = @ZCOS0020-ZZBGD
    AND SPRAS = @SY-LANGU.

*-- 투자여부 내역
 SELECT SINGLE ZZIVCTX INTO @ZCOS0020-ZZIVCTXT
   FROM ZCOT0020T
  WHERE ZZIVC = @ZCOS0020-ZZIVC
    AND SPRAS = @SY-LANGU.

*-- 사업장유무내역
 SELECT SINGLE ZZBAGTX INTO @ZCOS0020-ZZBAGTX
   FROM ZCOT1070T
  WHERE ZZBAG = @ZCOS0020-ZZBAG
    AND SPRAS = @SY-LANGU.

*-- 행정구역내역
 SELECT SINGLE ZZADTTX INTO @ZCOS0020-ZZADTTX
   FROM ZCOT1090T
  WHERE ZZADT = @ZCOS0020-ZZADT
    AND SPRAS = @SY-LANGU.

*-- 발주처 유형내역
 SELECT SINGLE ZZPRGTX INTO @ZCOS0020-ZZPRGTX
   FROM ZCOT1100T
  WHERE ZZPRG = @ZCOS0020-ZZPRG
    AND SPRAS = @SY-LANGU.

*-- H/W 하위본부내역
 SELECT SINGLE ZZHWBTX INTO @ZCOS0020-ZZHWBTX
   FROM ZCOT1110T
  WHERE ZZHWB = @ZCOS0020-ZZHWB
    AND SPRAS = @SY-LANGU.

*-- 통제유형내역
 SELECT SINGLE CTEXT INTO @ZCOS0020-ZZCYPTXT
   FROM ZCOT1130T
  WHERE CTYPE = @ZCOS0020-ZZCYP
    AND SPRAS = @SY-LANGU.

*-- 수주유형 내역
 SELECT SINGLE COTXT INTO @ZCOS0020-ZZCOPTXT
   FROM ZCOT1120T
  WHERE COTYP = @ZCOS0020-ZZCOP
    AND SPRAS = @SY-LANGU.
