*&---------------------------------------------------------------------*
*& Include          ZCOR0580SCR
*&---------------------------------------------------------------------*

SELECTION-SCREEN FUNCTION KEY 1.
SELECTION-SCREEN FUNCTION KEY 2.
SELECTION-SCREEN FUNCTION KEY 3.

SELECTION-SCREEN BEGIN OF BLOCK B01 WITH FRAME TITLE TEXT_S01.

PARAMETERS      P_KOKRS TYPE TKA01-KOKRS OBLIGATORY.
SELECT-OPTIONS  S_BUKRS FOR  T001-BUKRS  OBLIGATORY
                                         MATCHCODE OBJECT ZSH_BUKRS.
SELECT-OPTIONS  S_POSID FOR  PRPS-POSID.
PARAMETERS      P_VERSN TYPE TKA09-VERSN OBLIGATORY
                                         MATCHCODE OBJECT ZH_TKA09.

SELECTION-SCREEN END OF BLOCK B01.

SELECTION-SCREEN BEGIN OF BLOCK B02 WITH FRAME TITLE TEXT_S02.

PARAMETERS P_ACTUAL AS CHECKBOX.
PARAMETERS P_BDC    TYPE CTU_MODE MODIF ID BDC.

SELECTION-SCREEN END OF BLOCK B02.
