*&---------------------------------------------------------------------*
*& Include          ZCOR0640SCR
*&---------------------------------------------------------------------*

SELECTION-SCREEN FUNCTION KEY 1.

SELECTION-SCREEN: BEGIN OF BLOCK B01 WITH FRAME TITLE TEXT_S01.
PARAMETERS P_KOKRS TYPE TKA01-KOKRS   OBLIGATORY. " 관리회계영역
PARAMETERS P_BUKRS TYPE T001-BUKRS    OBLIGATORY. " 회사코드
PARAMETERS P_GJAHR TYPE CE11000-GJAHR OBLIGATORY. " 회계연도 : 현재일의 – 25 한 날자의 연도를 사용

  " 계획/실제: 기본값 실제
  SELECTION-SCREEN: BEGIN OF BLOCK BL1 WITH FRAME TITLE TEXT_S02.

  PARAMETERS P_ACT RADIOBUTTON GROUP RG1 DEFAULT 'X' USER-COMMAND UC01.

  " 계획버전 : 계획에만 해당
  SELECTION-SCREEN BEGIN OF LINE.
  PARAMETERS P_PLN RADIOBUTTON GROUP RG1.
  SELECTION-SCREEN COMMENT (30) TEXT_S04 FOR FIELD P_PLN.
  SELECTION-SCREEN COMMENT (10) TEXT_S05 FOR FIELD P_VERSI.
  PARAMETERS P_VERSI TYPE CE11000-VERSI MATCHCODE OBJECT ZH_TKA09.
  SELECTION-SCREEN END OF LINE.
  SELECTION-SCREEN: END OF BLOCK BL1.


  "
  SELECTION-SCREEN: BEGIN OF BLOCK BL2 WITH FRAME TITLE TEXT_S03.
  PARAMETERS: P_DTL RADIOBUTTON GROUP RG2 DEFAULT 'X',
              P_SUM RADIOBUTTON GROUP RG2.
  SELECTION-SCREEN: END OF BLOCK BL2.

SELECTION-SCREEN: END OF BLOCK B01.

*SELECTION-SCREEN COMMENT 1(80) TEXT-001.
