*&---------------------------------------------------------------------*
*& Include          ZCOR0670SCR
*&---------------------------------------------------------------------*

SELECTION-SCREEN FUNCTION KEY 1.
SELECTION-SCREEN FUNCTION KEY 2.

SELECTION-SCREEN: BEGIN OF BLOCK B01 WITH FRAME TITLE TEXT_S01.
PARAMETERS P_MENU  TYPE SETHEADER-SETNAME OBLIGATORY.
PARAMETERS P_BUKRS TYPE T001-BUKRS        OBLIGATORY.
PARAMETERS P_GJAHR TYPE GJAHR             OBLIGATORY.
PARAMETERS P_VERSI TYPE CE11000-VERSI     OBLIGATORY.
SELECTION-SCREEN COMMENT 40(30) TX_VERSI.
SELECTION-SCREEN: END OF BLOCK B01.

*SELECTION-SCREEN COMMENT 1(80) TEXT-001.
