*&---------------------------------------------------------------------*
*& Include          ZCOR0600SCR
*&---------------------------------------------------------------------*

SELECTION-SCREEN FUNCTION KEY 1.

SELECTION-SCREEN BEGIN OF BLOCK B01 WITH FRAME TITLE TEXT_S01.

PARAMETERS     P_KOKRS TYPE TKA01-KOKRS OBLIGATORY.
SELECT-OPTIONS S_BUKRS FOR  T001-BUKRS.
SELECT-OPTIONS S_ZZIZW FOR  PRPS-ZZIZW.
SELECT-OPTIONS S_ZZCD1 FOR  PRPS-ZZCD1.
SELECT-OPTIONS S_POSID FOR  PRPS-POSID.
SELECT-OPTIONS S_ERDAT FOR  PRPS-ERDAT  NO-EXTENSION.

SELECTION-SCREEN END OF BLOCK B01.

SELECTION-SCREEN BEGIN OF BLOCK B02 WITH FRAME TITLE TEXT_S02.

" 정산규칙 상세정보 조회
PARAMETERS P_DETAIL AS CHECKBOX.

SELECTION-SCREEN END OF BLOCK B02.
