*&---------------------------------------------------------------------*
*& Include          ZCOR0640SCR
*&---------------------------------------------------------------------*

SELECTION-SCREEN FUNCTION KEY 1.
SELECTION-SCREEN FUNCTION KEY 2.
SELECTION-SCREEN FUNCTION KEY 3.
SELECTION-SCREEN FUNCTION KEY 4.

SELECTION-SCREEN: BEGIN OF BLOCK B01 WITH FRAME TITLE TEXT_S01.
PARAMETERS P_KOKRS TYPE TKA01-KOKRS   OBLIGATORY.
PARAMETERS P_GJAHR TYPE CE11000-GJAHR OBLIGATORY.
PARAMETERS P_PERDE TYPE CE11000-PERDE OBLIGATORY.
SELECTION-SCREEN: END OF BLOCK B01.

SELECTION-SCREEN: BEGIN OF BLOCK B02 WITH FRAME TITLE TEXT_S02.
PARAMETERS: P_FILE TYPE RLGRAP-FILENAME OBLIGATORY.
SELECTION-SCREEN: END OF BLOCK B02.

*SELECTION-SCREEN COMMENT 1(80) TEXT-001.
