*&---------------------------------------------------------------------*
*& Include          ZCOR0610SCR
*&---------------------------------------------------------------------*

SELECTION-SCREEN FUNCTION KEY 1.

SELECTION-SCREEN BEGIN OF BLOCK B01 WITH FRAME TITLE TEXT_S01.

PARAMETERS     P_KOKRS TYPE TKA01-KOKRS OBLIGATORY.
SELECT-OPTIONS S_BUKRS FOR  T001-BUKRS MEMORY ID BUK
                                       MATCHCODE OBJECT ZSH_BUKRS.
SELECT-OPTIONS S_ZZIZW FOR  PRPS-ZZIZW.
SELECT-OPTIONS S_ZZCD1 FOR  PRPS-ZZCD1.
SELECT-OPTIONS S_POSID FOR  PRPS-POSID.
SELECT-OPTIONS S_ERDAT FOR  PRPS-ERDAT NO-EXTENSION.
SELECT-OPTIONS S_GJAHR FOR  COSP-GJAHR NO-EXTENSION MEMORY ID GJR.
PARAMETERS     P_VERSN TYPE COSP-VERSN OBLIGATORY.

SELECTION-SCREEN END OF BLOCK B01.

SELECTION-SCREEN BEGIN OF BLOCK B02 WITH FRAME TITLE TEXT_S02.

PARAMETERS P_DTL_MN AS CHECKBOX.  " 월별 상세조회
PARAMETERS P_DTL_CE AS CHECKBOX.  " 원가요소별 상세조회
PARAMETERS P_INCLD  AS CHECKBOX.  " 약정 포함여부

SELECTION-SCREEN END OF BLOCK B02.
