*&---------------------------------------------------------------------*
*& Include          ZCOR0530SCR
*&---------------------------------------------------------------------*

SELECTION-SCREEN FUNCTION KEY 1.
SELECTION-SCREEN FUNCTION KEY 2.

SELECTION-SCREEN: BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-T01.
SELECTION-SCREEN: BEGIN OF LINE.
PARAMETERS PA_UPLD RADIOBUTTON GROUP RG1 USER-COMMAND UC1 DEFAULT 'X'.
SELECTION-SCREEN COMMENT (10) TEXT-S01 FOR FIELD PA_UPLD.
SELECTION-SCREEN POSITION 20.
PARAMETERS PA_DISP RADIOBUTTON GROUP RG1 .
SELECTION-SCREEN COMMENT (10) TEXT-S02 FOR FIELD PA_DISP.
SELECTION-SCREEN: END OF LINE.
SELECTION-SCREEN: END OF BLOCK B1.

SELECTION-SCREEN: BEGIN OF BLOCK B2 WITH FRAME TITLE TEXT-T02.
PARAMETERS: PA_FILE TYPE RLGRAP-FILENAME OBLIGATORY DEFAULT 'C:\' MODIF ID M01.
SELECTION-SCREEN SKIP 1.
PARAMETERS: PA_OVER AS CHECKBOX MODIF ID M01.
SELECTION-SCREEN: END OF BLOCK B2.

*SELECTION-SCREEN COMMENT 1(80) TEXT-001.
