*&---------------------------------------------------------------------*
*& Include          ZCOR0560SCR
*&---------------------------------------------------------------------*

SELECTION-SCREEN FUNCTION KEY 1.

SELECTION-SCREEN BEGIN OF BLOCK B01 WITH FRAME TITLE TEXT_S01.

PARAMETERS P_KOKRS  TYPE TKA01-KOKRS     OBLIGATORY.
PARAMETERS P_GJAHR  TYPE ACDOCA-GJAHR    OBLIGATORY.
SELECT-OPTIONS S_POPER FOR ACDOCA-POPER  OBLIGATORY NO-EXTENSION.
SELECT-OPTIONS S_BUKRS FOR ACDOCA-RBUKRS OBLIGATORY.

SELECTION-SCREEN END OF BLOCK B01.

SELECTION-SCREEN BEGIN OF BLOCK B02 WITH FRAME TITLE TEXT_S02.

  PARAMETERS P_WBS_P RADIOBUTTON GROUP RG1 DEFAULT 'X'.
  PARAMETERS P_WBS_E RADIOBUTTON GROUP RG1.
  PARAMETERS P_WBS_A RADIOBUTTON GROUP RG1.

SELECTION-SCREEN END OF BLOCK B02.


SELECTION-SCREEN BEGIN OF BLOCK B03 WITH FRAME TITLE TEXT_S03.

  PARAMETERS P_ACT    RADIOBUTTON GROUP RG2 DEFAULT 'X'
                                            USER-COMMAND UC_VT.

  SELECTION-SCREEN BEGIN OF LINE.
  PARAMETERS P_PLN    RADIOBUTTON GROUP RG2.
  SELECTION-SCREEN COMMENT (30) TEXT_S06 FOR FIELD P_PLN.
  SELECTION-SCREEN COMMENT (10) TEXT_S07 FOR FIELD P_VERSN.
  PARAMETERS P_VERSN  TYPE TKA09-VERSN MATCHCODE OBJECT ZH_TKA09 .
  SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN END OF BLOCK B03.

SELECTION-SCREEN BEGIN OF BLOCK B04 WITH FRAME TITLE TEXT_S04.

  PARAMETERS P_NOZERO AS CHECKBOX.
  PARAMETERS P_EXCLDM AS CHECKBOX.

SELECTION-SCREEN END OF BLOCK B04.
