*&---------------------------------------------------------------------*
*& Include          ZCOR0520SCR
*&---------------------------------------------------------------------*

SELECTION-SCREEN FUNCTION KEY 1.  "-- HELP

*--------------------------------------------------------------------*
SELECTION-SCREEN: BEGIN OF BLOCK B2 WITH FRAME TITLE TEXT-S01.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 4(12) TEXT-S02 FOR FIELD PA_R01.
SELECTION-SCREEN POSITION 30.
PARAMETERS: PA_R01 RADIOBUTTON GROUP RD2 .
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 4(12) TEXT-S03 FOR FIELD PA_R02.
SELECTION-SCREEN POSITION 30.
PARAMETERS: PA_R02 RADIOBUTTON GROUP RD2 .
SELECTION-SCREEN PUSHBUTTON 40(20) TEXT-S04 USER-COMMAND R02.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN: END OF BLOCK B2.
*--------------------------------------------------------------------*
